# Generated by Django 5.1.4 on 2025-01-19 15:33

import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContentBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('soft_delete', models.BooleanField(default=False)),
                ('time_created', models.DateTimeField(blank=True, null=True, verbose_name='creation time')),
                ('time_updated', models.DateTimeField(auto_now=True, null=True, verbose_name='update time')),
                ('time_deleted', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='deleted time')),
                ('title', models.CharField(max_length=255)),
                ('content_html', tinymce.models.HTMLField(blank=True, null=True)),
                ('content_text', models.TextField(blank=True, null=True)),
                ('content_json', models.JSONField(blank=True, default=dict)),
                ('block_type', models.CharField(choices=[('none', 'None'), ('html_text', 'Html Text Block'), ('button_next', 'Button (Next Lesson)'), ('button_continue', 'Button (Continue)'), ('choices_field', 'Choices Field'), ('input_gpt', 'Input to Chat GPT')], default='none', max_length=30)),
                ('order', models.PositiveIntegerField(db_index=True, default=0, editable=False)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('soft_delete', models.BooleanField(default=False)),
                ('time_created', models.DateTimeField(blank=True, null=True, verbose_name='creation time')),
                ('time_updated', models.DateTimeField(auto_now=True, null=True, verbose_name='update time')),
                ('time_deleted', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='deleted time')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('soft_delete', models.BooleanField(default=False)),
                ('time_created', models.DateTimeField(blank=True, null=True, verbose_name='creation time')),
                ('time_updated', models.DateTimeField(auto_now=True, null=True, verbose_name='update time')),
                ('time_deleted', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='deleted time')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('duration', models.CharField(blank=True, default='15 min', max_length=50, null=True)),
                ('is_free', models.BooleanField(default=False)),
                ('is_locked', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(db_index=True, default=0, editable=False)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('soft_delete', models.BooleanField(default=False)),
                ('time_created', models.DateTimeField(blank=True, null=True, verbose_name='creation time')),
                ('time_updated', models.DateTimeField(auto_now=True, null=True, verbose_name='update time')),
                ('time_deleted', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='deleted time')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('order', models.PositiveIntegerField(db_index=True, default=0, editable=False)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
