# Generated by Django 5.1.4 on 2025-01-26 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_group_module_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='module',
            name='course',
        ),
    ]
