# Generated by Django 5.1.4 on 2025-01-26 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_lesson_uuid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='uuid',
        ),
    ]
