# Generated by Django 5.1.4 on 2025-02-11 20:33

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_lesson_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentblock',
            name='uuid_temp',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
