# Generated by Django 5.1.4 on 2025-02-12 12:02

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0011_contentblock_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentblock',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
