# Generated by Django 5.1.4 on 2025-05-03 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0012_alter_contentblock_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='prompt',
            field=models.TextField(blank=True, help_text='Prompt for ChatGPT. If empty, the lesson will be without a prompt.', null=True),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='title',
            field=models.CharField(help_text='the special character `$` will be replaced by a sequence number', max_length=255),
        ),
        migrations.AlterField(
            model_name='module',
            name='title',
            field=models.CharField(help_text='the special character `$` will be replaced by a sequence number', max_length=255),
        ),
    ]
