# Generated by Django 5.1.4 on 2025-05-07 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0013_lesson_prompt_alter_lesson_title_alter_module_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='is_free',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='is_locked',
        ),
        migrations.CreateModel(
            name='Access',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Название пакета доступа', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Описание того, что входит в пакет', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Когда пакет был создан')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Когда пакет был в последний раз обновлён')),
                ('lessons', models.ManyToManyField(help_text='Какие уроки включает этот пакет', related_name='access_bundles', to='courses.lesson')),
            ],
            options={
                'verbose_name': 'Access Bundle',
                'verbose_name_plural': 'Access Bundles',
                'ordering': ['name'],
            },
        ),
    ]
