# Generated by Django 5.1.4 on 2025-05-08 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0014_remove_lesson_is_free_remove_lesson_is_locked_access'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='is_free',
            field=models.BooleanField(default=False, help_text='If True, the lesson will be available for free.'),
        ),
    ]
