# Generated by Django 5.1.4 on 2025-05-08 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0015_lesson_is_free'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('ru', 'Русский'), ('cs', 'Čeština')], default='ru', help_text='Language of the course', max_length=6),
        ),
    ]
