# Generated by Django 5.1.4 on 2025-05-15 10:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0016_course_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='lesson_en',
            field=models.ForeignKey(blank=True, help_text='English version of the lesson. If empty, the lesson will be without a prompt.', null=True, on_delete=django.db.models.deletion.CASCADE, to='courses.lesson'),
        ),
    ]
