# Generated by Django 5.1.4 on 2025-05-19 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0017_lesson_lesson_en'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='prompt',
        ),
    ]
