# Generated by Django 5.1.4 on 2025-06-12 08:41

import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0018_remove_lesson_prompt'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentblock',
            name='uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AddIndex(
            model_name='contentblock',
            index=models.Index(fields=['lesson', 'order'], name='content_block_lesson_order_idx'),
        ),
        migrations.AddIndex(
            model_name='contentblock',
            index=models.Index(fields=['block_type'], name='content_block_type_idx'),
        ),
        migrations.AddIndex(
            model_name='contentblock',
            index=models.Index(fields=['lesson', 'block_type', 'order'], name='lesson_block_type_order_idx'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['language'], name='course_language_idx'),
        ),
        migrations.AddIndex(
            model_name='group',
            index=models.Index(fields=['course', 'order'], name='group_course_order_idx'),
        ),
        migrations.AddIndex(
            model_name='lesson',
            index=models.Index(fields=['module', 'order'], name='lesson_module_order_idx'),
        ),
        migrations.AddIndex(
            model_name='lesson',
            index=models.Index(fields=['is_free'], name='lesson_is_free_idx'),
        ),
        migrations.AddIndex(
            model_name='lesson',
            index=models.Index(fields=['lesson_en'], name='lesson_english_version_idx'),
        ),
        migrations.AddIndex(
            model_name='module',
            index=models.Index(fields=['group', 'order'], name='module_group_order_idx'),
        ),
    ]
