
version: "3.7"

services:
  postgres:
    image: postgres:16
    environment:
      - POSTGRES_DB=yourdb            
      - POSTGRES_USER=youruser        
      - POSTGRES_PASSWORD=yourpassword
    volumes:
      - ./data/n8n/postgres16:/var/lib/postgresql/data
    networks:
      - n8n-network
    deploy:
      replicas: 1
      restart_policy:
        condition: any

  n8n:
    image: docker.n8n.io/n8nio/n8n
    ports:
      - target: 5678
        published: 5678
        protocol: tcp
        mode: host
    environment:
      - DB_TYPE=postgresdb
      - DB_POSTGRESDB_DATABASE=yourdb     
      - DB_POSTGRESDB_HOST=postgres       
      - DB_POSTGRESDB_PORT=5432            
      - DB_POSTGRESDB_USER=youruser        
      - DB_POSTGRESDB_PASSWORD=yourpassword
    volumes:
      - ./data/n8n/data:/home/node/.n8n
    networks:
      - n8n-network
    depends_on:
      - postgres
    deploy:
      replicas: 1
      restart_policy:
        condition: any

networks:
  n8n-network:



version: "3.7"

services:
  postgres:
    image: postgres:16
    environment:
      - POSTGRES_DB=yourdb           # Название базы данных PostgreSQL
      - POSTGRES_USER=youruser       # Пользователь PostgreSQL
      - POSTGRES_PASSWORD=yourpassword  # Пароль для пользователя PostgreSQL
    volumes:
      - ./data/n8n/postgres16:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: always

  n8n:
    image: docker.n8n.io/n8nio/n8n
    environment:
      - DB_TYPE=postgresdb
      - DB_POSTGRESDB_DATABASE=yourdb          # Название базы данных
      - DB_POSTGRESDB_HOST=postgres            # Имя сервиса PostgreSQL, указанное ниже
      - DB_POSTGRESDB_PORT=5432                 # Порт PostgreSQL
      - DB_POSTGRESDB_USER=youruser             # Пользователь PostgreSQL
      - DB_POSTGRESDB_SCHEMA=public             # Схема, обычно "public"
      - DB_POSTGRESDB_PASSWORD=yourpassword     # Пароль PostgreSQL
    ports:
      - "5678:5678"
    volumes:
      - ./data/n8n/data:/home/node/.n8n
    restart: always