#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset

uv run python manage.py migrate
uv run python manage.py collectstatic --noinput
uv run python -m gunicorn webapp.asgi:application -k uvicorn.workers.UvicornWorker \
    --bind 0.0.0.0:8020 \
    --workers 4
