const QUERY_KEYS = {
  USER_DATA: 'USER_DATA',
  MODULE_DATA: 'MODULE_DATA',
  LESSON_DATA: 'LESSON_DATA',
  LESSON_PROGRESS: 'LESSON_PROGRESS',
  LESSON_NEXT_DATA: 'LESSON_NEXT_DATA',
};

export default QUERY_KEYS;
