const QUERY_KEYS = {
  USER_DATA: 'USER_DATA',
  MODULE_DATA: 'MODULE_DATA',
  LESSON_DATA: 'LESSON_DATA',
  LESSON_PROGRESS: 'LESSON_PROGRESS',
  LESSON_NEXT_DATA: 'LESSON_NEXT_DATA',
  REGISTER_REQUEST: 'REGISTER_REQUEST',
  REGISTER: 'REGISTER',
  PAYMENTS_PARAMS: 'PAYMENTS_PARAMS',
  PRODUCT_DATA: 'PRODUCT_DATA',
};

export default QUERY_KEYS;
