# Generated by Django 5.1.4 on 2025-03-14 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openai_chats', '0002_option'),
    ]

    operations = [
        migrations.AlterField(
            model_name='option',
            name='parameters',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
