# Generated by Django 5.1.4 on 2025-05-19 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openai_chats', '0003_alter_option_parameters'),
    ]

    operations = [
        migrations.AddField(
            model_name='option',
            name='global_prompt',
            field=models.TextField(blank=True, help_text='Global prompt for the chat. This will be used as a system message.', null=True),
        ),
    ]
