# Generated by Django 5.1.4 on 2025-05-20 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openai_chats', '0004_option_global_prompt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmessage',
            name='role',
            field=models.CharField(choices=[('user', 'User'), ('assistant', 'Assistant'), ('system', 'System'), ('developer', 'Developer')], max_length=50),
        ),
    ]
