# Generated by Django 5.1.4 on 2025-06-02 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openai_chats', '0005_alter_chatmessage_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='token_input',
            field=models.PositiveIntegerField(default=0, help_text='Number of tokens used in the input messages'),
        ),
        migrations.AddField(
            model_name='chat',
            name='token_output',
            field=models.PositiveIntegerField(default=0, help_text='Number of tokens used in the output messages'),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='model_used',
            field=models.CharField(blank=True, help_text='Model used for generating this message', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='token_count',
            field=models.PositiveIntegerField(default=0, help_text='Number of tokens used in this message'),
        ),
    ]
