# Generated by Django 5.1.4 on 2025-06-02 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openai_chats', '0006_chat_token_input_chat_token_output_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='option',
            name='is_active_lesson_context',
            field=models.BooleanField(default=True, help_text='If True, the chat will use lesson context for generating responses.'),
        ),
    ]
