# Generated by Django 5.1.4 on 2025-01-10 12:33

import django.db.models.deletion
import tinymce.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('soft_delete', models.BooleanField(default=False)),
                ('time_created', models.DateTimeField(blank=True, null=True, verbose_name='creation time')),
                ('time_updated', models.DateTimeField(auto_now=True, null=True, verbose_name='update time')),
                ('time_deleted', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='deleted time')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('user_created', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='created by user')),
                ('user_deleted', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='deleted by user')),
                ('user_updated', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='updated by user')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('soft_delete', models.BooleanField(default=False)),
                ('time_created', models.DateTimeField(blank=True, null=True, verbose_name='creation time')),
                ('time_updated', models.DateTimeField(auto_now=True, null=True, verbose_name='update time')),
                ('time_deleted', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='deleted time')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('user_created', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='created by user')),
                ('user_deleted', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='deleted by user')),
                ('user_updated', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='updated by user')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ContentBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('soft_delete', models.BooleanField(default=False)),
                ('time_created', models.DateTimeField(blank=True, null=True, verbose_name='creation time')),
                ('time_updated', models.DateTimeField(auto_now=True, null=True, verbose_name='update time')),
                ('time_deleted', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='deleted time')),
                ('title', models.CharField(max_length=255)),
                ('content_html', tinymce.models.HTMLField(blank=True, null=True)),
                ('content_text', models.TextField(blank=True, null=True)),
                ('content_json', models.JSONField(blank=True, default=dict)),
                ('block_type', models.CharField(choices=[('html_text', 'Html Text Block'), ('button_next', 'Button (Next)'), ('button_continue', 'Button (Continue)'), ('choices_field', 'Choices Field'), ('input_gpt', 'Input to Chat GPT')], default='text', max_length=30)),
                ('order', models.PositiveIntegerField(db_index=True, default=0, editable=False)),
                ('user_created', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='created by user')),
                ('user_deleted', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='deleted by user')),
                ('user_updated', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='updated by user')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cources.lesson')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('soft_delete', models.BooleanField(default=False)),
                ('time_created', models.DateTimeField(blank=True, null=True, verbose_name='creation time')),
                ('time_updated', models.DateTimeField(auto_now=True, null=True, verbose_name='update time')),
                ('time_deleted', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='deleted time')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cources.course')),
                ('user_created', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='created by user')),
                ('user_deleted', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='deleted by user')),
                ('user_updated', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='updated by user')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='lesson',
            name='module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cources.module'),
        ),
    ]
