# Generated by Django 5.1.4 on 2025-01-02 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cources', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentblock',
            name='inline_ordering_position',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='contentblock',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
