# Generated by Django 5.1.4 on 2025-01-10 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cources', '0002_alter_course_description_alter_lesson_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentblock',
            name='block_type',
            field=models.CharField(choices=[('html_text', 'Html Text Block'), ('button_next', 'Button (Next)'), ('button_continue', 'Button (Continue)'), ('choices_field', 'Choices Field'), ('input_gpt', 'Input to Chat GPT')], default='html_text', max_length=30),
        ),
    ]
