# Generated by Django 5.1.4 on 2025-01-02 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cources', '0002_contentblock_inline_ordering_position_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contentblock',
            name='inline_ordering_position',
        ),
    ]
