# Generated by Django 5.1.4 on 2025-01-02 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cources', '0003_remove_contentblock_inline_ordering_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentblock',
            name='order',
            field=models.PositiveIntegerField(db_index=True, default=0, editable=False),
        ),
    ]
