# Generated by Django 5.1.4 on 2025-01-10 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cources', '0003_alter_contentblock_block_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lesson',
            options={'ordering': ['order']},
        ),
        migrations.AlterModelOptions(
            name='module',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='lesson',
            name='order',
            field=models.PositiveIntegerField(db_index=True, default=0, editable=False),
        ),
        migrations.AddField(
            model_name='module',
            name='order',
            field=models.PositiveIntegerField(db_index=True, default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='contentblock',
            name='block_type',
            field=models.CharField(choices=[('none', 'None'), ('html_text', 'Html Text Block'), ('button_next', 'Button (Next Lesson)'), ('button_continue', 'Button (Continue)'), ('choices_field', 'Choices Field'), ('input_gpt', 'Input to Chat GPT')], default='none', max_length=30),
        ),
    ]
