# Generated by Django 5.1.4 on 2025-01-17 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cources', '0004_alter_lesson_options_alter_module_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='duration',
            field=models.CharField(blank=True, default='15 min', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='lesson',
            name='is_locked',
            field=models.BooleanField(default=True),
        ),
    ]
