# Generated by Django 5.1.4 on 2025-01-17 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cources', '0005_lesson_duration_lesson_is_locked'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='is_free',
            field=models.BooleanField(default=False),
        ),
    ]
