"""
Django settings for webapp project.

Generated by 'django-admin startproject' using Django 4.1.3.

For more information on this file, see
https://docs.djangoproject.com/en/4.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.1/ref/settings/
"""

import os
# from core.utils import get_data_depoy
# from .version import VERSION_API as VAPI
from pathlib import Path
from decouple import config
from decouple import Csv
from dj_database_url import parse as db_url
# from core.logger import LOG
from datetime import timedelta

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config('SECRET_KEY', default='django-insecure-c%@zyw#h$&@ga*+cbpqf5l!-z4pm9e)q0@rvjfl1hx=rvc!&nw')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config('DEBUG', default=True, cast=bool)

ALLOWED_HOSTS = config('ALLOWED_HOSTS', default='*', cast=Csv())

CSRF_TRUSTED_ORIGINS = config(
    'CSRF_TRUSTED_ORIGINS',
    default='http://localhost:5173',
    cast=Csv()
)

CORS_ORIGIN_WHITELIST = (
       'http://localhost:5173',
)

CORS_ALLOWED_ORIGINS = [
    "http://localhost:8000",
    "http://localhost:5173",
]

SITE_ID = 1

# https://github.com/jazzband/django-tinymce/issues/354
X_FRAME_OPTIONS = 'SAMEORIGIN'
# https://issueantenna.com/repo/jazzband/django-tinymce/issues/389
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

# CORS_ALLOW_CREDENTIALS = True
# CORS_ORIGIN_ALLOW_ALL = True


# Application definition

INSTALLED_APPS = [
    'jazzmin',
    'tinymce',
    'adminsortable',
    # 'djangocms_admin_style',
    # 'django.contrib.sites',
    # 'sekizai',
    # 'cms',
    # 'menus',
    # 'treebeard',

    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'corsheaders',
    'rest_framework',
    'rest_framework_simplejwt',
    'rest_framework_simplejwt.token_blacklist',
    'drf_spectacular',
    'django_filters',

    'core',
    'courses',
    'payments',
    'users'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',

    # https://whitenoise.readthedocs.io/en/latest/
    "whitenoise.middleware.WhiteNoiseMiddleware",

    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',

    # #cms
    # "django.middleware.locale.LocaleMiddleware",

    # "cms.middleware.user.CurrentUserMiddleware",
    # "cms.middleware.page.CurrentPageMiddleware",
    # "cms.middleware.toolbar.ToolbarMiddleware",
    # "cms.middleware.language.LanguageCookieMiddleware",

]

ROOT_URLCONF = 'webapp.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            # 'templates',
            os.path.join(BASE_DIR, 'templates'),
            os.path.join(
                BASE_DIR,
                'docs',
                '_build'
            ),
            os.path.join(BASE_DIR, 'dist'),
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',

                # #cms
                # 'django.template.context_processors.i18n',
                # 'sekizai.context_processors.sekizai',
                # 'cms.context_processors.cms_settings',
            ],
        },
    },
]
# https://whitenoise.readthedocs.io/en/latest/
STORAGES = {
    # ...
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
    },
}

WSGI_APPLICATION = 'webapp.wsgi.application'

REST_FRAMEWORK = {
    'DEFAULT_RENDERER_CLASSES': [
        'rest_framework.renderers.JSONRenderer',
        # 'rest_framework.renderers.BrowsableAPIRenderer',

    ],
    'DEFAULT_FILTER_BACKENDS': [
        'django_filters.rest_framework.DjangoFilterBackend'
    ],
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ],
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
}

# REST_KNOX = {
#     "TOKEN_TTL": timedelta(days=7),  # AuthToken expiration time
#     "AUTH_HEADER_PREFIX": "Bearer",
# }

SPECTACULAR_SETTINGS = {
    'TITLE': "Trader Note API",
    'DESCRIPTION': ' API for development',
    'VERSION': "0.0.1",
    # "SERVE_INCLUDE_SCHEMA": False,
    # "SCHEMA_PATH_PREFIX": r"/api/v[0-9]",
    # "SCHEMA_PATH_PREFIX_TRIM": True,
    # "SWAGGER_UI_SETTINGS": {
    #     "deepLinking": True,
    #     "displayOperationId": True,
    # },
}

# Database
# https://docs.djangoproject.com/en/4.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}
# DATABASES = {
#     'default': config(
#         'DATABASE_URL',
#         default='postgres://user:password@127.0.0.1:5432/db_name',
#         cast=db_url
#     )
# }


# Password validation
# https://docs.djangoproject.com/en/4.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.1/topics/i18n/

LANGUAGE_CODE = config("LANGUAGE_CODE", default='en')

TIME_ZONE = config("TIME_ZONE", default="Europe/Prague")

USE_I18N = config("USE_I18N", default=True, cast=bool)

USE_TZ = config("USE_TZ", default=True, cast=bool)


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.1/howto/static-files/

STATIC_ROOT = os.path.join(BASE_DIR, "static")
STATIC_URL = '/static/'

STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'frontend/dist/static'),
]

MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
MEDIA_URL = '/media/'

DOCS_ROOT = os.path.join(BASE_DIR, 'docs', '_build', 'html')
DOCS_URL = '/docs/'

# Default primary key field type
# https://docs.djangoproject.com/en/4.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

AUTH_USER_MODEL = "users.CourseUser"

# JAZZMIN SETTINGS
JAZZMIN_SETTINGS = {
    # title of the window (Will default to current_admin_site.site_title if absent or None)
    "site_title": "Trader Note",

    # Title on the brand, and login screen (19 chars max) (defaults to current_admin_site.site_header if absent or None)
    "site_header": "Welcome to Trader Note!",

    # Welcome text on the login screen
    "welcome_sign": "Log in",

    # Copyright on the footer
    "copyright": config(
        "FOOTOR_NAME", default="v0.0.1 ()"
        # + '<a href="/docs/changelog.html"'
        # + ' target="_blank">'
        # + 'DOCS</a>'
        ),
}

JAZZMIN_UI_TWEAKS = {
}


TINYMCE_DEFAULT_CONFIG = {
    # 'theme': 'modern',
    'height': 300,
    # 'plugins': 'advlist autolink link image lists charmap print preview hr anchor pagebreak',
    "plugins": [
        "advlist", "anchor", "autolink", "code", "fullscreen",
        "help", "image", "insertdatetime", "link", "media",
        "preview", "searchreplace", "table", "accordion"
    ],
    'toolbar': "undo redo | styles | bold italic underline strikethrough | align | bullist numlist | searchreplace",
}
