# Generated by Django 5.1.4 on 2025-01-26 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='subscriptiontype',
            name='duration_value',
            field=models.PositiveIntegerField(blank=True, help_text='Number of months', null=True),
        ),
    ]
