# Generated by Django 5.1.4 on 2025-05-07 12:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_alter_subscription_start_date_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Human-readable title of the product', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Optional detailed description', null=True)),
                ('price', models.DecimalField(decimal_places=2, help_text='Product price', max_digits=10)),
                ('currency', models.CharField(default='USD', help_text='ISO-4217 currency code', max_length=3)),
                ('is_active', models.BooleanField(default=True, help_text='Флаг, доступен ли продукт для покупки')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Когда продукт был создан')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Когда продукт был в последний раз обновлён')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CloudPaymentTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(help_text='CloudPayments TransactionId', max_length=255, unique=True)),
                ('invoice_id', models.CharField(blank=True, help_text='Your own order/invoice identifier (InvoiceId)', max_length=255, null=True)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Transaction amount', max_digits=10)),
                ('currency', models.CharField(default='RUB', help_text='ISO-4217 currency code', max_length=3)),
                ('status', models.CharField(choices=[('AUTHORIZED', 'Authorized'), ('CONFIRMED', 'Confirmed'), ('DECLINED', 'Declined'), ('REFUNDED', 'Refunded')], default='AUTHORIZED', help_text='Current status of the transaction', max_length=20)),
                ('card_type', models.CharField(blank=True, help_text='Тип карты (Visa, MasterCard и т.п.)', max_length=50, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP-адрес клиента на момент оплаты', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Дата и время создания записи')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Дата и время последнего обновления записи')),
                ('raw_data', models.JSONField(blank=True, default=dict, help_text='Полный JSON-ответ от CloudPayments')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cloudpayments_transactions', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(blank=True, help_text='Product associated with the transaction', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='payments.product')),
            ],
            options={
                'verbose_name': 'CloudPayments Transaction',
                'verbose_name_plural': 'CloudPayments Transactions',
                'ordering': ['-created_at'],
            },
        ),
    ]
