# Generated by Django 5.1.4 on 2025-05-25 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_product_cloudpaymenttransaction'),
    ]

    operations = [
        migrations.CreateModel(
            name='CloudPaymentOptions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('params', models.JSONField(blank=True, default=dict, help_text='Настройки CloudPayments, например, public_key, secret_key и т.д.')),
            ],
        ),
    ]
