# Generated by Django 5.1.4 on 2025-06-02 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0005_product_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cloudpaymenttransaction',
            name='status',
            field=models.CharField(choices=[('AUTHORIZED', 'Authorized'), ('COMPLETED', 'Completed'), ('CONFIRMED', 'Confirmed'), ('DECLINED', 'Declined'), ('REFUNDED', 'Refunded')], default='AUTHORIZED', help_text='Current status of the transaction', max_length=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, default=999999.99, help_text='Product price', max_digits=10),
        ),
    ]
