# Generated by Django 5.1.4 on 2025-03-02 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_userlessonprogress_procent_progress'),
    ]

    operations = [
        migrations.AddField(
            model_name='userlessonprogress',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
    ]
