# Generated by Django 5.1.4 on 2025-05-07 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_courseuser_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseuser',
            name='language',
            field=models.CharField(choices=[('ru', 'Russian'), ('en', 'English'), ('cz', 'Czech')], default='ru', max_length=2, verbose_name='Preferred Language'),
        ),
    ]
