# Generated by Django 5.1.4 on 2025-05-08 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0015_lesson_is_free'),
        ('users', '0006_courseuser_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseuser',
            name='access',
            field=models.ManyToManyField(blank=True, help_text='Access to lessons', related_name='users', to='courses.access'),
        ),
    ]
