# Generated by Django 5.1.4 on 2025-05-08 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_courseuser_access'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseuser',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('ru', 'Русский'), ('cs', 'Čeština')], default='ru', max_length=6, verbose_name='Preferred Language'),
        ),
    ]
