# Generated by Django 5.1.4 on 2025-05-21 14:06

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_userreview'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseuser',
            name='uuid',
            field=models.UUIDField(blank=True, default=uuid.uuid4, null=True),
        ),
    ]
