# Generated by Django 5.1.4 on 2025-06-12 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0019_alter_contentblock_uuid_alter_lesson_uuid_and_more'),
        ('users', '0011_courseuser_uuid_unique'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userlessonprogress',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='userreview',
            unique_together=set(),
        ),
        migrations.AddIndex(
            model_name='userlessonprogress',
            index=models.Index(fields=['user', 'lesson'], name='user_lesson_progress_idx'),
        ),
        migrations.AddIndex(
            model_name='userlessonprogress',
            index=models.Index(fields=['user', 'is_completed'], name='user_completed_lessons_idx'),
        ),
        migrations.AddIndex(
            model_name='userlessonprogress',
            index=models.Index(fields=['last_seen_block'], name='last_seen_block_idx'),
        ),
        migrations.AddIndex(
            model_name='userreview',
            index=models.Index(fields=['user', 'lesson'], name='user_review_idx'),
        ),
        migrations.AddConstraint(
            model_name='userlessonprogress',
            constraint=models.UniqueConstraint(fields=('user', 'lesson'), name='unique_user_lesson_progress'),
        ),
        migrations.AddConstraint(
            model_name='userreview',
            constraint=models.UniqueConstraint(fields=('user', 'lesson'), name='unique_user_lesson_review'),
        ),
    ]
